-- Refreshes all materialized views on Pau to get referential data from Cergy
-- Run as GLPI_OWNER on Pau node

EXEC DBMS_MVIEW.REFRESH('MV_SITE', 'C');
EXEC DBMS_MVIEW.REFRESH('MV_LOCATION', 'C');
EXEC DBMS_MVIEW.REFRESH('MV_TYPE_MATERIEL', 'C');
EXEC DBMS_MVIEW.REFRESH('MV_CONSTRUCTEUR', 'C');
EXEC DBMS_MVIEW.REFRESH('MV_MODELE', 'C');
EXEC DBMS_MVIEW.REFRESH('MV_TYPE_EQUIPEMENT_RESEAU', 'C');
EXEC DBMS_MVIEW.REFRESH('MV_GROUPE', 'C');
EXEC DBMS_MVIEW.REFRESH('MV_PROFIL', 'C');

-- Verify counts
SELECT 'MV_SITE' AS mv, COUNT(*) AS cnt FROM MV_SITE
UNION ALL SELECT 'MV_TYPE_MATERIEL', COUNT(*) FROM MV_TYPE_MATERIEL
UNION ALL SELECT 'MV_CONSTRUCTEUR', COUNT(*) FROM MV_CONSTRUCTEUR;
EXIT;