-- perf/00_mv_logs_cergy.sql
-- Run as GLPI_OWNER on Cergy (port 1521)

CREATE MATERIALIZED VIEW LOG ON SITE
    WITH PRIMARY KEY (code, nom, adresse)
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON LOCATION
    WITH PRIMARY KEY (site_id, batiment, etage, salle)
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON TYPE_MATERIEL
    WITH PRIMARY KEY (libelle)
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON CONSTRUCTEUR
    WITH PRIMARY KEY (nom)
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON MODELE
    WITH PRIMARY KEY (constructeur_id, type_materiel_id, reference)
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON TYPE_EQUIPEMENT_RESEAU
    WITH PRIMARY KEY (libelle)
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON GROUPE
    WITH PRIMARY KEY (nom, description)
    INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON PROFIL
    WITH PRIMARY KEY (nom, description)
    INCLUDING NEW VALUES;

GRANT SELECT ON MLOG$_SITE                   TO link_user;
GRANT SELECT ON MLOG$_LOCATION               TO link_user;
GRANT SELECT ON MLOG$_TYPE_MATERIEL          TO link_user;
GRANT SELECT ON MLOG$_CONSTRUCTEUR           TO link_user;
GRANT SELECT ON MLOG$_MODELE                 TO link_user;
GRANT SELECT ON MLOG$_TYPE_EQUIPEMENT_RESEAU TO link_user;
GRANT SELECT ON MLOG$_GROUPE                 TO link_user;
GRANT SELECT ON MLOG$_PROFIL                 TO link_user;

SELECT master, log_table FROM user_mview_logs ORDER BY master;

EXIT;
