-- schema/01_tablespaces_pau.sql
-- Run as SYSTEM on Pau node (port 1522)
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE TBS_REFERENTIEL
    DATAFILE 'tbs_referentiel.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE TBS_UTILISATEURS
    DATAFILE 'tbs_utilisateurs.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE TBS_MATERIELS
    DATAFILE 'tbs_materiels.dbf' SIZE 100M AUTOEXTEND ON NEXT 20M MAXSIZE 1G;

CREATE TABLESPACE TBS_RESEAU
    DATAFILE 'tbs_reseau.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE TABLESPACE TBS_AUDIT
    DATAFILE 'tbs_audit.dbf' SIZE 100M AUTOEXTEND ON NEXT 20M MAXSIZE 1G;

CREATE TABLESPACE TBS_INDEX
    DATAFILE 'tbs_index.dbf' SIZE 100M AUTOEXTEND ON NEXT 20M MAXSIZE 1G;

-- Verify
SELECT tablespace_name FROM dba_tablespaces WHERE tablespace_name LIKE 'TBS_%' ORDER BY tablespace_name;

EXIT;
