-- schema/04_owner_cergy.sql
-- Run as SYSTEM on Cergy node (port 1521)
ALTER SESSION SET CONTAINER = XEPDB1;

-- ============================================================
-- Schema owner
-- ============================================================
CREATE USER GLPI_OWNER IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_MATERIELS
    QUOTA UNLIMITED ON TBS_REFERENTIEL
    QUOTA UNLIMITED ON TBS_UTILISATEURS
    QUOTA UNLIMITED ON TBS_MATERIELS
    QUOTA UNLIMITED ON TBS_RESEAU
    QUOTA UNLIMITED ON TBS_AUDIT
    QUOTA UNLIMITED ON TBS_INDEX;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE MATERIALIZED VIEW,
      CREATE DATABASE LINK, CREATE CLUSTER, CREATE SYNONYM, CREATE JOB
    TO GLPI_OWNER;

-- Verify
SELECT username FROM dba_users
WHERE username = 'GLPI_OWNER';

EXIT;
