-- schema/04_users_roles_pau.sql
-- Run as SYSTEM on Pau node (port 1522)
-- Identical structure to cergy version
-- Database links are created in perf/ task (not here)
ALTER SESSION SET CONTAINER = FREEPDB1;

-- ============================================================
-- Schema owner
-- ============================================================
CREATE USER GLPI_OWNER IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_MATERIELS
    QUOTA UNLIMITED ON TBS_REFERENTIEL
    QUOTA UNLIMITED ON TBS_UTILISATEURS
    QUOTA UNLIMITED ON TBS_MATERIELS
    QUOTA UNLIMITED ON TBS_RESEAU
    QUOTA UNLIMITED ON TBS_AUDIT
    QUOTA UNLIMITED ON TBS_INDEX;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE MATERIALIZED VIEW,
      CREATE DATABASE LINK, CREATE CLUSTER, CREATE SYNONYM, CREATE JOB
    TO GLPI_OWNER;

-- ============================================================
-- Roles (same as Cergy)
-- ============================================================
CREATE ROLE ROLE_ADMIN_PARC;
CREATE ROLE ROLE_TECH_RESEAU;
CREATE ROLE ROLE_GESTION_USERS;
CREATE ROLE ROLE_CONSULT;
CREATE ROLE ROLE_AUDITEUR;

-- ROLE_ADMIN_PARC
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.MATERIEL           TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.ATTRIBUTION        TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.EQUIPEMENT_RESEAU  TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.PORT_RESEAU        TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.VLAN               TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.SITE                   TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.LOCATION               TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.UTILISATEUR            TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.TYPE_MATERIEL          TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.CONSTRUCTEUR           TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.MODELE                 TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.TYPE_EQUIPEMENT_RESEAU TO ROLE_ADMIN_PARC;

-- ROLE_TECH_RESEAU
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.EQUIPEMENT_RESEAU  TO ROLE_TECH_RESEAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.PORT_RESEAU        TO ROLE_TECH_RESEAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.VLAN               TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.MATERIEL               TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.UTILISATEUR            TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.SITE                   TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.LOCATION               TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.TYPE_EQUIPEMENT_RESEAU TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.TYPE_MATERIEL          TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.CONSTRUCTEUR           TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.MODELE                 TO ROLE_TECH_RESEAU;

-- ROLE_GESTION_USERS
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.UTILISATEUR        TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.UTILISATEUR_GROUPE TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.UTILISATEUR_PROFIL TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.GROUPE             TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.PROFIL             TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.MATERIEL    TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.ATTRIBUTION TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.SITE        TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.LOCATION    TO ROLE_GESTION_USERS;

-- ROLE_AUDITEUR
GRANT SELECT ON GLPI_OWNER.JOURNAL_AUDIT TO ROLE_AUDITEUR;

-- ============================================================
-- Demo users
-- ============================================================
CREATE USER admin_parc IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_UTILISATEURS;
GRANT ROLE_ADMIN_PARC TO admin_parc;
GRANT CREATE SESSION TO admin_parc;

CREATE USER tech_reseau IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_RESEAU;
GRANT ROLE_TECH_RESEAU TO tech_reseau;
GRANT CREATE SESSION TO tech_reseau;

CREATE USER gestion_users IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_UTILISATEURS;
GRANT ROLE_GESTION_USERS TO gestion_users;
GRANT CREATE SESSION TO gestion_users;

CREATE USER consultant IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_UTILISATEURS;
GRANT ROLE_CONSULT TO consultant;
GRANT CREATE SESSION TO consultant;

CREATE USER auditeur IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_AUDIT;
GRANT ROLE_AUDITEUR TO auditeur;
GRANT CREATE SESSION TO auditeur;

-- ============================================================
-- Database link user (for BDDR)
-- ============================================================
CREATE USER link_user IDENTIFIED BY link123
    DEFAULT TABLESPACE TBS_REFERENTIEL;
GRANT CREATE SESSION TO link_user;

GRANT SELECT ON GLPI_OWNER.SITE                   TO link_user;
GRANT SELECT ON GLPI_OWNER.LOCATION               TO link_user;
GRANT SELECT ON GLPI_OWNER.TYPE_MATERIEL          TO link_user;
GRANT SELECT ON GLPI_OWNER.CONSTRUCTEUR           TO link_user;
GRANT SELECT ON GLPI_OWNER.MODELE                 TO link_user;
GRANT SELECT ON GLPI_OWNER.TYPE_EQUIPEMENT_RESEAU TO link_user;
GRANT SELECT ON GLPI_OWNER.GROUPE                 TO link_user;
GRANT SELECT ON GLPI_OWNER.PROFIL                 TO link_user;
GRANT SELECT ON GLPI_OWNER.MATERIEL               TO link_user;
GRANT SELECT ON GLPI_OWNER.UTILISATEUR            TO link_user;
GRANT SELECT ON GLPI_OWNER.EQUIPEMENT_RESEAU      TO link_user;

-- Verify
SELECT username FROM dba_users
WHERE username IN ('GLPI_OWNER','ADMIN_PARC','TECH_RESEAU','GESTION_USERS','CONSULTANT','AUDITEUR','LINK_USER')
ORDER BY username;

SELECT role FROM dba_roles WHERE role LIKE 'ROLE_%' ORDER BY role;

EXIT;
