-- schema/05_users_roles_cergy.sql
-- Run as SYSTEM on Cergy node (port 1521), after GLPI_OWNER tables exist
ALTER SESSION SET CONTAINER = FREEPDB1;

-- ============================================================
-- Roles
-- ============================================================
CREATE ROLE ROLE_ADMIN_PARC;
CREATE ROLE ROLE_TECH_RESEAU;
CREATE ROLE ROLE_GESTION_USERS;
CREATE ROLE ROLE_CONSULT;
CREATE ROLE ROLE_AUDITEUR;

-- ROLE_ADMIN_PARC: CRUD on materiels, attributions, equipements reseau
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.MATERIEL           TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.ATTRIBUTION        TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.EQUIPEMENT_RESEAU  TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.PORT_RESEAU        TO ROLE_ADMIN_PARC;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.VLAN               TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.SITE                   TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.LOCATION               TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.UTILISATEUR            TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.TYPE_MATERIEL          TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.CONSTRUCTEUR           TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.MODELE                 TO ROLE_ADMIN_PARC;
GRANT SELECT ON GLPI_OWNER.TYPE_EQUIPEMENT_RESEAU TO ROLE_ADMIN_PARC;
-- EXECUTE on packages granted after packages are compiled (see plsql task)

-- ROLE_TECH_RESEAU: CRUD on reseau, read-only on materiels/utilisateurs
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.EQUIPEMENT_RESEAU  TO ROLE_TECH_RESEAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.PORT_RESEAU        TO ROLE_TECH_RESEAU;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.VLAN               TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.MATERIEL               TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.UTILISATEUR            TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.SITE                   TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.LOCATION               TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.TYPE_EQUIPEMENT_RESEAU TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.TYPE_MATERIEL          TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.CONSTRUCTEUR           TO ROLE_TECH_RESEAU;
GRANT SELECT ON GLPI_OWNER.MODELE                 TO ROLE_TECH_RESEAU;

-- ROLE_GESTION_USERS: CRUD on utilisateurs/groupes/profils, read-only on materiels
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.UTILISATEUR        TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.UTILISATEUR_GROUPE TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.UTILISATEUR_PROFIL TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.GROUPE             TO ROLE_GESTION_USERS;
GRANT SELECT, INSERT, UPDATE, DELETE ON GLPI_OWNER.PROFIL             TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.MATERIEL    TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.ATTRIBUTION TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.SITE        TO ROLE_GESTION_USERS;
GRANT SELECT ON GLPI_OWNER.LOCATION    TO ROLE_GESTION_USERS;

-- ROLE_CONSULT: SELECT on business views (granted after views created in perf task)

-- ROLE_AUDITEUR: SELECT on audit journal
GRANT SELECT ON GLPI_OWNER.JOURNAL_AUDIT TO ROLE_AUDITEUR;

-- ============================================================
-- Demo users
-- ============================================================
CREATE USER admin_parc IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_UTILISATEURS;
GRANT ROLE_ADMIN_PARC TO admin_parc;
GRANT CREATE SESSION TO admin_parc;

CREATE USER tech_reseau IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_RESEAU;
GRANT ROLE_TECH_RESEAU TO tech_reseau;
GRANT CREATE SESSION TO tech_reseau;

CREATE USER gestion_users IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_UTILISATEURS;
GRANT ROLE_GESTION_USERS TO gestion_users;
GRANT CREATE SESSION TO gestion_users;

CREATE USER consultant IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_UTILISATEURS;
GRANT ROLE_CONSULT TO consultant;
GRANT CREATE SESSION TO consultant;

CREATE USER auditeur IDENTIFIED BY admin123
    DEFAULT TABLESPACE TBS_AUDIT;
GRANT ROLE_AUDITEUR TO auditeur;
GRANT CREATE SESSION TO auditeur;

-- ============================================================
-- Database link user (for BDDR)
-- ============================================================
CREATE USER link_user IDENTIFIED BY link123
    DEFAULT TABLESPACE TBS_REFERENTIEL;
GRANT CREATE SESSION TO link_user;

GRANT SELECT ON GLPI_OWNER.SITE                   TO link_user;
GRANT SELECT ON GLPI_OWNER.LOCATION               TO link_user;
GRANT SELECT ON GLPI_OWNER.TYPE_MATERIEL          TO link_user;
GRANT SELECT ON GLPI_OWNER.CONSTRUCTEUR           TO link_user;
GRANT SELECT ON GLPI_OWNER.MODELE                 TO link_user;
GRANT SELECT ON GLPI_OWNER.TYPE_EQUIPEMENT_RESEAU TO link_user;
GRANT SELECT ON GLPI_OWNER.GROUPE                 TO link_user;
GRANT SELECT ON GLPI_OWNER.PROFIL                 TO link_user;
GRANT SELECT ON GLPI_OWNER.MATERIEL               TO link_user;
GRANT SELECT ON GLPI_OWNER.UTILISATEUR            TO link_user;
GRANT SELECT ON GLPI_OWNER.EQUIPEMENT_RESEAU      TO link_user;

-- Verify
SELECT username FROM dba_users
WHERE username IN ('GLPI_OWNER','ADMIN_PARC','TECH_RESEAU','GESTION_USERS','CONSULTANT','AUDITEUR','LINK_USER')
ORDER BY username;

SELECT role FROM dba_roles WHERE role LIKE 'ROLE_%' ORDER BY role;

EXIT;
